services:
  postgres:
    image: postgres:16-alpine
    container_name: account-service-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - account-service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  account-redis:
    image: redis:7-alpine
    env_file:
      - ../.env
    container_name: account-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - account-service-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  account-service-network:
    driver: bridge