grpc:
  server:
    port: ${GRPC_PORT}

server:
  port: ${SERVER_PORT}

spring:
  application:
    name: account-service

  import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    deserialization:
      fail-on-unknown-properties: true  # ? ????????? ??????? ? ???????????? ??????


  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework: WARN
    org.hibernate: WARN